name: Upload latest data to github release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
    - uses: addnab/docker-run-action@v3
      with:
        registry: docker.io
        image: chenditc/investment_data:latest
        options: -v ${{ github.workspace }}:/output
        run: |
          bash -c "bash dump_qlib_bin.sh && cp ./qlib_bin.tar.gz /output/"

    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: qlib_bin.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
