name: Upload latest data to github release

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 7 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        file: Dockerfile
        asset_name: Dockerfile
        tag: ${{ github.ref }}
        overwrite: true
        body: "Daily update release"
